### ISSUE TITLE
Violates Chrome store policies. Appears to have disappeared from the store

### ISSUE THREAD

**Issue by MaffooBristol** [OhMyGuus/I-Still-Dont-Care-About-Cookies#2253]
What's going on?

![image](https://user-images.githubusercontent.com/3296828/218311157-6b59acc6-16bf-4594-ab69-1f9774114930.png)

![image](https://user-images.githubusercontent.com/3296828/218311181-15d82727-b329-4ffc-87cf-00ae3abc3194.png)

**Comment by sebastienserre** [comment]
Same here :(

**Comment by bonesandflowers** [comment]
Same here. I bypassed it by downloading the .zip file and added it to extensions in developer mode. So far it seems to work.

**Comment by luetage** [comment]
Ha, I was just about to recommend the extension to someone and the webstore link 404ed. There is no good reason, Avast probably bombarded it with reports? Silly conspiracy theory, but who knows ^^

**Comment by OhMyGuus** [comment]
Yeah this is quite sad, we got removed from the chrome store. The reason for this is a bit confusing for me because they asked me last month to add a privacy policy to my chrome profile which I did but for some reason they still decided to remove it from the store. 

Going to contact support and hope they can give more info about it, but having low hopes.

**Comment by sebastienserre** [comment]
isn't a matter from Avast and their Chrome extension addon name ?
You choose a really near name (that we can understand) but maybe having a more generic name should help.

**Comment by luetage** [comment]
> isn't a matter from Avast and their Chrome extension addon name ? You choose a really near name (that we can understand) but maybe having a more generic name should help.

Yeah, I think it’s because of “impersonating” another extension, the name might not have been a wise choice. Funnily enough there is another extension named “Still don’t care about cookies,” which isn’t blocked. I’d still say Avast intervened.

**Comment by OhMyGuus** [comment]
> isn't a matter from Avast and their Chrome extension addon name ?
> You choose a really near name (that we can understand) but maybe having a more generic name should help.

as far as I know its just the privacy policy... 

![Screenshot_2023-02-12-18-46-00-673-edit_com.google.android.gm.jpg](https://user-images.githubusercontent.com/12090928/218327813-8c2b29c8-4a03-48f6-ae1c-986f34036262.jpg)

![Screenshot_2023-02-12-18-48-13-354-edit_com.google.android.gm.jpg](https://user-images.githubusercontent.com/12090928/218327814-bb7fa50a-935f-469e-82a0-fe9cee6c8ee9.jpg)

**Comment by luetage** [comment]
I have two extensions up and never added a privacy policy link to my account. What they were keen on was updating the privacy practices field for each extension a year ago. Maybe they are stricter with extensions that are over a certain threshold of users, but it still seems strange to me.

**Comment by OhMyGuus** [comment]
> I have two extensions up and never added a privacy policy link to my account. What they were keen on was updating the privacy practices field for each extension a year ago. Maybe they are stricter with extensions that are over a certain threshold of users, but it still seems strange to me.

Yeah same it feels and is a bit weird however I've just filled in the contact form,  and hope that we get a response...

**Comment by OhMyGuus** [comment]
Small update I was able to submit v1.1.1, it's now under review and I hope they will just add it back. I'm sorry for the inconvenience, I think they should have be made it more clear that I needed to do a new release after adding the policy but yeah...

**Comment by MaffooBristol** [comment]
Oh I'm glad that there's nothing dodgy going on from your side. Thanks so much for putting in the effort to sort this out. Best of luck and hope you can sort it out. Let me know if there's anything I can do to help!

**Comment by Rusenche** [comment]
https://chrome.google.com/webstore/detail/i-still-dont-care-about-c/edibdbjcniadpccecjdfdjjppcpchdlm/ The new version is now available. ;}

**Comment by OhMyGuus** [comment]
![Screenshot_2023-02-13-10-17-35-716_com.google.android.gm.jpg](https://user-images.githubusercontent.com/12090928/218418378-640297c4-b450-45a2-99f9-e472118b71f6.jpg)

Yeah apperently it needed an release to get the changes to my developer account profile approved (atleast I think). It wasn't clear to me when they send the first email but oh well, we atleast got back to the store 🎉

**Comment by OhMyGuus** [comment]
![Screenshot_2023-02-13-10-21-19-048-edit_com.google.android.gm.jpg](https://user-images.githubusercontent.com/12090928/218419246-cbb95371-5951-4668-8386-867eaae36a00.jpg)


 Yeah apperently it needed an release to get the changes to my developer account profile approved (atleast I think). It wasn't clear to me when they send the first email but oh well, we atleast got back to the store 🎉

**Comment by Rusenche** [comment]
As you can see - the developer of this project abandoned it **3 months ago**. Since then there is not a single change and the extension on some sites interferes and the extension has been disabled for me for two months... It is noted that the requests are over **2200**, the developer apparently abandoned this extension...

**Comment by OhMyGuus** [comment]
> As you can see - the developer of this project abandoned it **3 months ago**. Since then there is not a single change and the extension on some sites interferes and the extension has been disabled for me for two months... It is noted that the requests are over **2200**, the developer apparently abandoned this extension...

Unfortunately, this is partially true. I had to postpone this project for a couple of months due to an extremely busy and stressful period in my studies. However, that phase is nearly over, and I will gradually start to have time for this project again. 
The planning is to have all the big sites that got reported again fixed next week and then slowly work through all the reported websites the week after. Sorry all for this delay.

**Comment by Enrico204** [comment]
@OhMyGuus maybe you can see if there is anyone willing to help maintain the extension? I don't have time right now, but maybe someone can :-)

**Comment by shayded-exe** [comment]
I don't think a system that requires manual rules for every site is sustainable.

What about an approach that tries to detect the popups and clicks either "necessary only" or deny or unchecks the checkboxes (you get the idea). It would be a lot more scalable and could probably cover 90% of sites without too many special conditions.

**Comment by d4k0** [comment]
@OhMyGuus 
Is there an approximate timeframe for when you'll have time for the add-on again? Unfortunately, the add-on no longer works on more and more sites, and even on Mozilla's add-on page, the first negative reviews are already coming in.

@shayded-exe 
There are already add-ons that try to support all cookie frameworks (they are called consent management platform (CMP)), but even these often do not work so well depending on the country. Here is a selection that is still somewhat maintained:

https://addons.mozilla.org/de/firefox/addon/consent-o-matic/
https://addons.mozilla.org/de/firefox/addon/super-agent/
https://addons.mozilla.org/de/firefox/addon/cookieblock/

Some time ago I had also found the add-ons "do not consent" and "never consent", but these seem to have been deleted by the respective developers. One of these two worked best for me.

Ghostery is supposed to be able to do that by now, too:

https://www.ghostery.com/blog/never-consent-by-ghostery

**Comment by Rusenche** [comment]
> @d4k0
> @OhMyGuus Is there an approximate timeframe for when you'll have time for the add-on again? Unfortunately, the add-on no longer works on more and more sites, and even on Mozilla's add-on page, the first negative reviews are already coming in.
> 
> @shayded-exe There are already add-ons that try to support all cookie frameworks (they are called consent management platform (CMP)), but even these often do not work so well depending on the country. Here is a selection that is still somewhat maintained:
> 
> https://addons.mozilla.org/de/firefox/addon/consent-o-matic/ https://addons.mozilla.org/de/firefox/addon/super-agent/ https://addons.mozilla.org/de/firefox/addon/cookieblock/
> 
> Some time ago I had also found the add-ons "do not consent" and "never consent", but these seem to have been deleted by the respective developers. One of these two worked best for me.
> 
> Ghostery is supposed to be able to do that by now, too, but they collect data (at least they used to):
> 
> https://www.ghostery.com/blog/never-consent-by-ghostery



Almost 5 months ago I wrote that the developer abandoned the development of this extension. Nothing has changed since then. The only change is that at that time the requests were 2200 and today they are already 4400.

There is not a single new version since I wrote nearly 5 months ago. There won't be a new version either, because requests will soon exceed 5000, and such requests are almost impossible to process in terms of time. Don't wait for this project to continue. Its development was completed when it appeared.

I recommend https://github.com/wanhose/cookie-dialog-monster/

**Comment by d4k0** [comment]
@Rusenche 
Thanks for your tip. Unfortunately, development for Firefox (my main browser) has been halted or interrupted for reasons not explained:

"Mozilla Firefox (development stalled until further notice)".
Source: https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#compatibility

The last version of Firefox in the add-on store is from June 2022. I tested Cookie Dialog Monster with Firefox some time ago, unfortunately there were some page that didn't work. But I will test it again with a Chrome based browser.

**Comment by Rusenche** [comment]
> @d4k0
> @Rusenche Thanks for your tip. Unfortunately, development for Firefox (my main browser) has been halted or interrupted for reasons not explained:
> 
> "Mozilla Firefox (development stalled until further notice)". Source: https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#compatibility
> 
> The last version of Firefox in the add-on store is from June 2022. I tested Cookie Dialog Monster with Firefox some time ago, unfortunately there were some page that didn't work. But I will test it again with a Chrome based browser.

@d4k0
I don't use Firefox and had no idea that new versions were not supported for it browser. And since you wrote about Firefox - out of curiosity I checked how it is with Edge and it turned out that there are new versions.

> @d4k0
> I tested Cookie Dialog Monster with Firefox some time ago, unfortunately there were some page that didn't work.

@d4k0
I encountered 2 problem sites, I wrote to the developer, and along with the two problem sites, new problems appeared. And despite all this - he - the developer actively communicates. I had suggested some options for him to add and now it's all a fact. It publishes new versions and I am very happy. Even now, posting my opinion here, I'm going to write to the developer of `Cookie dialog monster` to thank him for the new version because he fixed the problems I wrote him about, but now I noticed a new problem. Why I write in such detail - because it responds and publishes new versions and fixes problem sites when users report it.

Addendum: I'm using `Ungoogled Chromium v.117.0.5938.150 x64`.
